/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGmxReader,
  IGmxReaderInterface,
} from "../../interfaces/IGmxReader";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_vault",
        type: "address",
      },
      {
        internalType: "address",
        name: "_tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "_tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amountIn",
        type: "uint256",
      },
    ],
    name: "getAmountOut",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGmxReader__factory {
  static readonly abi = _abi;
  static createInterface(): IGmxReaderInterface {
    return new utils.Interface(_abi) as IGmxReaderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGmxReader {
    return new Contract(address, _abi, signerOrProvider) as IGmxReader;
  }
}
