/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { IGmxReader } from "./IGmxReader";
export type { IGmxRouter } from "./IGmxRouter";
export type { IGmxVault } from "./IGmxVault";
export type { IUniswapV2Router } from "./IUniswapV2Router";
