/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Arbitrage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Arbitrage__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IGmxReader",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGmxReader__factory>;
    getContractFactory(
      name: "IGmxRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGmxRouter__factory>;
    getContractFactory(
      name: "IGmxVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGmxVault__factory>;
    getContractFactory(
      name: "IUniswapV2Router",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV2Router__factory>;

    getContractAt(
      name: "Arbitrage",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Arbitrage>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IGmxReader",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IGmxReader>;
    getContractAt(
      name: "IGmxRouter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IGmxRouter>;
    getContractAt(
      name: "IGmxVault",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IGmxVault>;
    getContractAt(
      name: "IUniswapV2Router",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV2Router>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
